const STORAGE_KEY = 'af-command-center:v1';
const seed = {
  programme:{name:'BSc (Hons) Accounting and Finance',partner:'SIM Global Education × University of Birmingham',structure:'2-year top-up; Year 2 = 25% of final, Year 3 = 75%',credits_per_year:120},
  courses:[
    {id:'y2-financial-reporting',name:'Financial Reporting',year:'Year 2',blurb:'How companies prepare and present financial statements under IFRS — the language of corporate accounting.',examRelevance:'high',status:'not-started',confidence:0,keyTopics:['IFRS framework','Income statement & balance sheet preparation','Statement of cash flows','Revenue recognition (IFRS 15)','Inventories, PPE, intangibles','Group accounts / consolidation basics'].map(t=>({text:t,done:false})),resources:[],notes:''},
    {id:'y2-management-accounting',name:'Management Accounting',year:'Year 2',blurb:'Accounting for internal decision-making: costing, budgeting, and performance measurement.',examRelevance:'high',status:'not-started',confidence:0,keyTopics:['Cost classification & behaviour','Absorption vs marginal costing','CVP analysis','Budgeting & variance analysis','Standard costing','Short-term decision-making'].map(t=>({text:t,done:false})),resources:[],notes:''},
    {id:'y2-corporate-finance',name:'Corporate Finance',year:'Year 2',blurb:'How firms make investment, financing, and dividend decisions to maximise value.',examRelevance:'high',status:'not-started',confidence:0,keyTopics:['Time value of money','NPV, IRR, payback','Risk and return / CAPM','Cost of capital (WACC)','Capital structure','Dividend policy'].map(t=>({text:t,done:false})),resources:[],notes:''},
    {id:'y2-audit',name:'Audit',year:'Year 2',blurb:'How auditors gather evidence to express an opinion on whether financial statements are fairly presented.',examRelevance:'medium',status:'not-started',confidence:0,keyTopics:['Assurance & audit objectives','Audit risk model','Materiality','Internal control','Audit evidence & sampling','Audit opinion & reports','Professional ethics'].map(t=>({text:t,done:false})),resources:[],notes:''},
    {id:'y2-taxation',name:'Taxation: Principles and Planning',year:'Year 2',blurb:'Foundations of tax: how individuals and companies are taxed, and basic planning principles.',examRelevance:'medium',status:'not-started',confidence:0,keyTopics:['Tax residency','Individual income tax','Corporate income tax','GST / VAT basics','Tax filing & compliance','Basic tax planning principles'].map(t=>({text:t,done:false})),resources:[],notes:''},
    {id:'y2-business-law',name:'Business Law',year:'Year 2',blurb:'Legal framework for business: contract, agency, company law. Already familiar from prior study.',examRelevance:'low',status:'previewing',confidence:2,keyTopics:['Contract law','Tort & negligence','Agency','Partnership & company law','Employment basics'].map(t=>({text:t,done:false})),resources:[],notes:'Already covered in earlier studies — quick review only.'},
    {id:'y3-advanced-finance',name:'Advanced Finance',year:'Year 3',blurb:'Builds on Corporate Finance: advanced valuation, M&A, risk management, international finance.',examRelevance:'high',status:'not-started',confidence:0,keyTopics:[],resources:[],notes:''},
    {id:'y3-advanced-financial-accounting',name:'Advanced Financial Accounting Practice and Theory',year:'Year 3',blurb:'Advanced reporting topics and the theoretical underpinnings of accounting standards.',examRelevance:'high',status:'not-started',confidence:0,keyTopics:[],resources:[],notes:''},
    {id:'y3-research-project',name:'Accounting and Finance Research Project',year:'Year 3',blurb:'Independent research project applying theory and analytical skills to a chosen AF topic.',examRelevance:'high',status:'not-started',confidence:0,keyTopics:[],resources:[],notes:''},
    {id:'y3-optional',name:'Optional Module Slot',year:'Year 3',blurb:'Placeholder for Year 3 elective — to be selected closer to the time.',examRelevance:'low',status:'not-started',confidence:0,keyTopics:[],resources:[],notes:''}
  ]
};
let state = loadState(); let filter='all'; let expanded = new Set();
function loadState(){const raw=localStorage.getItem(STORAGE_KEY); if(!raw){localStorage.setItem(STORAGE_KEY, JSON.stringify(seed)); return structuredClone(seed);} try{return JSON.parse(raw);}catch{return structuredClone(seed);}}
let timer; function persist(){clearTimeout(timer); timer=setTimeout(()=>localStorage.setItem(STORAGE_KEY, JSON.stringify(state)),300);} 
function route(){return location.hash.slice(1)||'/';}
const placeholders={
  '/':'Aggregated dashboard. Will show today\'s study tasks, current 4-month phase, progress across all subjects, energy check-in, and recent brain dump entries.',
  '/study/cfa':'Roadmap for CFA Level I/II/III with topic checklists and overlap mapping to UoB modules.',
  '/study/acca':'Roadmap for current and future ACCA qualification structures.',
  '/study/plan':'Phase-based study plan for the pre-university holiday: Accounting Foundation, Finance Foundation, UoB Preview, Audit/Tax Preview, CFA/ACCA orientation, reset week.',
  '/study/resource':'Cross-module library of YouTube/Bilibili/PDF/web resources with filtering and progress tracking.',
  '/study/upload':'Upload PDF/PPT/docs and use Claude API to extract summaries, key terms, checklists, flashcards, and quiz questions.',
  '/study/modes':'Browse, Checklist, Flashcard, Quiz, and Explain modes for active recall.',
  '/study/ai':'Conversational planner that suggests minimum-effort study plans based on energy level, progress, and upcoming travel.',
  '/life/travel':'Travel destinations, dates, and budget. Will integrate with the 4-Month Plan to auto-adjust workload.',
  '/life/braindump':'Quick capture for stray thoughts, todos, and life admin.'
};
function titleFromPath(p){return p==='/'?'Home':p.split('/').pop().replace('-', ' ').replace(/\b\w/g,c=>c.toUpperCase());}
function stars(n){return '★★★★★'.slice(0,n)+'☆☆☆☆☆'.slice(0,5-n);} 
function render(){const p=route(); document.getElementById('app').innerHTML=`
<nav class="nav"><a class="nav-item link" href="#/">Home</a>
<div class="nav-item">Study<div class="menu">
${[['/study/sim-uob','SIM UoB'],['/study/cfa','CFA'],['/study/acca','ACCA'],['/study/plan','4-Month Plan'],['/study/resource','Resource Library'],['/study/upload','Upload & Extract'],['/study/modes','Study Modes'],['/study/ai','AI Agent']].map(([u,l])=>`<a class="${p===u?'active':''}" href="#${u}">${l}</a>`).join('')}
</div></div>
<div class="nav-item">Life<div class="menu"><a href="#/life/travel">Travel & Rest</a><a href="#/life/braindump">Brain Dump</a></div></div></nav>
<main class="page">${p==='/study/sim-uob'?simPage():placeholderPage(p)}</main>`;
 bindEvents();}
function placeholderPage(p){return `<section class="placeholder"><h1>${titleFromPath(p)}</h1><p class="muted">This module is planned for a future version. Below is what it will eventually do.</p><ul><li>${placeholders[p]||'Planned module.'}</li></ul><span class="tag">v0.2</span></section>`}
function simPage(){const c=state.courses.filter(x=>filter==='all'||x.status===filter); const groups={'Year 2':c.filter(x=>x.year==='Year 2'),'Year 3':c.filter(x=>x.year==='Year 3')};return `<h1>SIM UoB Accounting & Finance</h1><p class="muted">BSc (Hons) — Year 2 (25%) + Year 3 (75%)</p><div class="toolbar"><select id="filter"><option value="all">all</option><option value="not-started">not-started</option><option value="previewing">previewing</option><option value="studying">studying</option><option value="done">done</option></select><button id="export">Export JSON</button><button id="import">Import JSON</button><button id="reset">Reset to seed</button><input type="file" id="import-file" accept="application/json" style="display:none"></div>${Object.entries(groups).map(([year,list])=>`<h2>${year}</h2><div class="grid">${list.map(card).join('')}</div>`).join('')}`;}
function card(course){const isExp=expanded.has(course.id); return `<article class="card course" data-id="${course.id}"><h3>${course.name}</h3><div class="muted">${course.blurb}</div><div class="badges"><span class="badge">${course.status}</span><span class="badge">${course.examRelevance}</span><span class="badge">${stars(course.confidence)}</span></div>${isExp?`<div class="expanded" data-stop="1"><div class="row"><label>Status <select data-field="status">${['not-started','previewing','studying','done'].map(v=>`<option ${course.status===v?'selected':''} value="${v}">${v}</option>`).join('')}</select></label><label>Relevance <select data-field="examRelevance">${['low','medium','high'].map(v=>`<option ${course.examRelevance===v?'selected':''} value="${v}">${v}</option>`).join('')}</select></label><label>Confidence <select data-field="confidence">${[0,1,2,3,4,5].map(v=>`<option ${course.confidence===v?'selected':''} value="${v}">${stars(v)}</option>`)}</select></label></div><strong>Key Topics</strong><ul class="topics">${course.keyTopics.map((t,i)=>`<li><input data-topic-check="${i}" type="checkbox" ${t.done?'checked':''}><input data-topic-text="${i}" value="${t.text}"><button data-topic-del="${i}">Delete</button></li>`).join('')}</ul><button data-topic-add="1">Add topic</button><strong>Resources</strong>${course.resources.map((r,i)=>`<div class="resource-item"><a class="link" href="${r.url}" target="_blank">${r.title}</a><span class="badge">${r.type}</span><button data-resource-del="${i}">Delete</button></div>`).join('')}<div class="row"><input placeholder="Title" data-res-title><input placeholder="URL" data-res-url><select data-res-type>${['youtube','bilibili','pdf','web','note'].map(x=>`<option>${x}</option>`)}</select><button data-resource-add="1">Add</button></div><label>Notes<textarea data-notes>${course.notes||''}</textarea></label></div>`:''}</article>`;}
function bindEvents(){const f=document.getElementById('filter'); if(f){f.value=filter;f.onchange=e=>{filter=e.target.value;render();};}
const ex=document.getElementById('export'); if(ex)ex.onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}); const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`af-command-center-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();};
const imp=document.getElementById('import'); if(imp)imp.onclick=()=>document.getElementById('import-file').click();
const inp=document.getElementById('import-file'); if(inp) inp.onchange=(e)=>{const file=e.target.files[0]; if(!file)return; const r=new FileReader(); r.onload=()=>{try{const data=JSON.parse(r.result); if(!Array.isArray(data.courses)) throw new Error(); if(confirm('This will replace all current data. Continue?')){state=data;persist();render();}}catch{alert('Invalid JSON file');}};r.readAsText(file);};
const reset=document.getElementById('reset'); if(reset) reset.onclick=()=>{if(confirm('Reset to seed data?')){state=structuredClone(seed);persist();render();}};
for(const el of document.querySelectorAll('.course')){el.addEventListener('click',(e)=>{if(e.target.closest('[data-stop]'))return; const id=el.dataset.id; expanded.has(id)?expanded.delete(id):expanded.add(id); render();});
const id=el.dataset.id; const course=state.courses.find(c=>c.id===id); if(!course)continue;
el.querySelectorAll('select[data-field]').forEach(s=>s.onchange=(e)=>{course[e.target.dataset.field]=e.target.dataset.field==='confidence'?Number(e.target.value):e.target.value;persist();render();});
const notes=el.querySelector('[data-notes]'); if(notes)notes.onblur=(e)=>{course.notes=e.target.value;persist();};
el.querySelectorAll('[data-topic-check]').forEach(i=>i.onchange=e=>{course.keyTopics[e.target.dataset.topicCheck].done=e.target.checked;persist();});
el.querySelectorAll('[data-topic-text]').forEach(i=>i.onblur=e=>{course.keyTopics[e.target.dataset.topicText].text=e.target.value;persist();});
el.querySelectorAll('[data-topic-del]').forEach(b=>b.onclick=e=>{course.keyTopics.splice(Number(e.target.dataset.topicDel),1);persist();render();});
const addT=el.querySelector('[data-topic-add]'); if(addT) addT.onclick=()=>{course.keyTopics.push({text:'New topic',done:false});persist();render();};
el.querySelectorAll('[data-resource-del]').forEach(b=>b.onclick=e=>{course.resources.splice(Number(e.target.dataset.resourceDel),1);persist();render();});
const addR=el.querySelector('[data-resource-add]'); if(addR)addR.onclick=()=>{const t=el.querySelector('[data-res-title]').value.trim();const u=el.querySelector('[data-res-url]').value.trim();const ty=el.querySelector('[data-res-type]').value; if(!t||!u)return; course.resources.push({id:crypto.randomUUID(),title:t,url:u,type:ty,addedAt:new Date().toISOString()});persist();render();};
}
}
window.addEventListener('hashchange', render); render();
